# ./infra/prometheus/prometheus.yml
global:
  scrape_interval: 15s # Intervalo de raspado por defecto

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Monitoreo del servicio Spring Boot 'auth-service'
  - job_name: 'auth-service'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    # Filtra solo los contenedores que tienen la etiqueta 'prometheus.io/scrape=true'
    relabel_configs:
      - source_labels: [__meta_docker_container_label_prometheus_io_scrape]
        regex: true
        action: keep
      # Reemplaza el path si está definido
      - source_labels: [__meta_docker_container_label_prometheus_io_path]
        regex: (.+)
        target_label: __metrics_path__
        action: replace
      # Reemplaza el puerto si está definido
      - source_labels: [__address__, __meta_docker_container_label_prometheus_io_port]
        regex: (.+):(?:\d+);(\d+)
        target_label: __address__
        replacement: $1:$2
        action: replace
      # Asigna el job name
      - source_labels: [__meta_docker_container_label_prometheus_io_job]
        target_label: job